### ISSUE TITLE
调用插件添加的路由OAuth Callback错误，提示 40011 “请登录...”

### ISSUE THREAD

**Issue by pkgplus** [BiteBit/yapi-plugin-auth2#2]
OAuth回调http://mydomain/api/plugin/oauth2/callback?code=XXXXXXXXX&state=STATE，报40011：

返回结果
```json
{
  "errcode": 40011,
  "errmsg": "请登录...",
  "data": null
}
```

yapi版本： v1.8.5

**Comment by amazing-gao** [comment]
你好。
YAPI不支持在外部配置ignoreRouter，并且YAPI框架对插件接口进行了登录状态校验（实际上不需要），
所以请在 https://github.com/YMFE/yapi/blob/master/server/controllers/base.js#L32 追加：
```js
    let ignoreRouter = [
      '/api/user/login_by_token',
      '/api/user/login',
      '/api/user/reg',
      '/api/user/status',
      '/api/user/logout',
      '/api/user/avatar',
      '/api/user/login_by_ldap',
      '/api/plugin/oauth2/callback' // yapi-plugin-auth2的插件路由
    ];
```

**Comment by aizhou01** [comment]
> 你好。
> YAPI不支持在外部配置ignoreRouter，并且YAPI框架对插件接口进行了登录状态校验（实际上不需要），
> 所以请在 https://github.com/YMFE/yapi/blob/master/server/controllers/base.js#L32 追加：
> 
> ```js
>     let ignoreRouter = [
>       '/api/user/login_by_token',
>       '/api/user/login',
>       '/api/user/reg',
>       '/api/user/status',
>       '/api/user/logout',
>       '/api/user/avatar',
>       '/api/user/login_by_ldap',
>       '/api/plugin/oauth2/callback' // yapi-plugin-auth2的插件路由
>     ];
> ```

确实有用，这么一大问题也没人修复

**Comment by amazing-gao** [comment]
> > 你好。
> > YAPI不支持在外部配置ignoreRouter，并且YAPI框架对插件接口进行了登录状态校验（实际上不需要），
> > 所以请在 https://github.com/YMFE/yapi/blob/master/server/controllers/base.js#L32 追加：
> > ```js
> >     let ignoreRouter = [
> >       '/api/user/login_by_token',
> >       '/api/user/login',
> >       '/api/user/reg',
> >       '/api/user/status',
> >       '/api/user/logout',
> >       '/api/user/avatar',
> >       '/api/user/login_by_ldap',
> >       '/api/plugin/oauth2/callback' // yapi-plugin-auth2的插件路由
> >     ];
> > ```
> 
> 确实有用，这么一大问题也没人修复

你的机会来了😀

**Comment by aizhou01** [comment]
> > > 你好。
> > > YAPI不支持在外部配置ignoreRouter，并且YAPI框架对插件接口进行了登录状态校验（实际上不需要），
> > > 所以请在 https://github.com/YMFE/yapi/blob/master/server/controllers/base.js#L32 追加：
> > > ```js
> > >     let ignoreRouter = [
> > >       '/api/user/login_by_token',
> > >       '/api/user/login',
> > >       '/api/user/reg',
> > >       '/api/user/status',
> > >       '/api/user/logout',
> > >       '/api/user/avatar',
> > >       '/api/user/login_by_ldap',
> > >       '/api/plugin/oauth2/callback' // yapi-plugin-auth2的插件路由
> > >     ];
> > > ```
> > 
> > 
> > 确实有用，这么一大问题也没人修复
> 
> 你的机会来了😀

你把插件安装文档写全也可以减少大家少走弯路。
