### ISSUE TITLE
1.9.2版本白屏

### ISSUE THREAD

**Issue by dustinyounglee** [BiteBit/yapi-plugin-auth2#5]
目前1.9.2版本装了以后白屏

**Comment by amazing-gao** [comment]
打开浏览器的调试模式，看下console有报什么错误没，发过来。

**Comment by dustinyounglee** [comment]
![image](https://user-images.githubusercontent.com/2144769/116508322-ac874e80-a8f3-11eb-9cb0-1d68ed8f29ad.png)
这个是console的报错，谢谢

**Comment by amazing-gao** [comment]
老铁，你这个情况YAPI本身的静态资源加载都404了，肯定白屏啊。建议你按照YAPI官方文档重新操作一遍。
