### ISSUE TITLE
配置后出现400

### ISSUE THREAD

**Issue by Keanhua** [BiteBit/yapi-plugin-auth2#6]
![image](https://user-images.githubusercontent.com/31396902/120281295-5854fd00-c2eb-11eb-9bf5-94e2f6ce5cd0.png)

**Comment by Keanhua** [comment]
这个是什么情况啊？

**Comment by amazing-gao** [comment]
应该是调用你的oauth接口报错了，可以打开console看下错误日志。

错误提示代码：https://github.com/amazing-gao/yapi-plugin-auth2/blob/master/controller.js#L60-L63

**Comment by Keanhua** [comment]
@amazing-gao 多谢，找到原因了，是我对接的这边是post请求
